#!/bin/bash

function createmanufacturer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturer.management.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.management.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/tlscacerts/ca.crt"

  # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.management.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/tlsca/tlsca.manufacturer.management.com-cert.pem"

  # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.management.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/ca/ca.manufacturer.management.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.management.com/peers/peer0.manufacturer.management.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.management.com/users/User1@manufacturer.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/users/User1@manufacturer.management.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.management.com/users/Admin@manufacturer.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.management.com/users/Admin@manufacturer.management.com/msp/config.yaml"
}

function createWasteCollectionCompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/WasteCollectionCompany.management.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-WasteCollectionCompany --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-WasteCollectionCompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-WasteCollectionCompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-WasteCollectionCompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-WasteCollectionCompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy WasteCollectionCompany's CA cert to WasteCollectionCompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/tlscacerts/ca.crt"

  # Copy WasteCollectionCompany's CA cert to WasteCollectionCompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/tlsca/tlsca.WasteCollectionCompany.management.com-cert.pem"

  # Copy WasteCollectionCompany's CA cert to WasteCollectionCompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/ca"
  cp "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/ca/ca.WasteCollectionCompany.management.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-WasteCollectionCompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering peer1"
  set -x
  fabric-ca-client register --caname ca-WasteCollectionCompany --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-WasteCollectionCompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-WasteCollectionCompany --id.name WasteCollectionCompanyadmin --id.secret WasteCollectionCompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls" --enrollment.profile tls --csr.hosts peer0.WasteCollectionCompany.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer0.WasteCollectionCompany.management.com/tls/server.key"

    echo "Generating the peer1 msp"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/msp/config.yaml"

  echo "Generating the peer1-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer1:peer1pw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls" --enrollment.profile tls --csr.hosts peer1.WasteCollectionCompany.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/peers/peer1.WasteCollectionCompany.management.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/users/User1@WasteCollectionCompany.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/users/User1@WasteCollectionCompany.management.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://WasteCollectionCompanyadmin:WasteCollectionCompanyadminpw@localhost:8054 --caname ca-WasteCollectionCompany -M "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/users/Admin@WasteCollectionCompany.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/WasteCollectionCompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/WasteCollectionCompany.management.com/users/Admin@WasteCollectionCompany.management.com/msp/config.yaml"
}

function creategovernment() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/government.management.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/government.management.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-government --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-government.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-government.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-government.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-government.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/government.management.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy government's CA cert to government's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.management.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.management.com/msp/tlscacerts/ca.crt"

  # Copy government's CA cert to government's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.management.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.management.com/tlsca/tlsca.government.management.com-cert.pem"

  # Copy government's CA cert to government's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.management.com/ca"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.management.com/ca/ca.government.management.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-government --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-government --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-government --id.name governmentadmin --id.secret governmentadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls" --enrollment.profile tls --csr.hosts peer0.government.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/government.management.com/peers/peer0.government.management.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.management.com/users/User1@government.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.management.com/users/User1@government.management.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://governmentadmin:governmentadminpw@localhost:10054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.management.com/users/Admin@government.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.management.com/users/Admin@government.management.com/msp/config.yaml"
}

function createrecyclingCenter() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/recyclingCenter.management.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-recyclingCenter --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-recyclingCenter.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-recyclingCenter.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-recyclingCenter.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-recyclingCenter.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy recyclingCenter's CA cert to recyclingCenter's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/tlscacerts/ca.crt"

  # Copy recyclingCenter's CA cert to recyclingCenter's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/tlsca/tlsca.recyclingCenter.management.com-cert.pem"

  # Copy recyclingCenter's CA cert to recyclingCenter's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/ca"
  cp "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/ca/ca.recyclingCenter.management.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-recyclingCenter --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-recyclingCenter --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-recyclingCenter --id.name recyclingCenteradmin --id.secret recyclingCenteradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-recyclingCenter -M "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-recyclingCenter -M "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls" --enrollment.profile tls --csr.hosts peer0.recyclingCenter.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/peers/peer0.recyclingCenter.management.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-recyclingCenter -M "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/users/User1@recyclingCenter.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/users/User1@recyclingCenter.management.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://recyclingCenteradmin:recyclingCenteradminpw@localhost:11054 --caname ca-recyclingCenter -M "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/users/Admin@recyclingCenter.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/recyclingCenter/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/recyclingCenter.management.com/users/Admin@recyclingCenter.management.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/management.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/management.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/management.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/management.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/management.com/msp/tlscacerts/tlsca.management.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/management.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/management.com/tlsca/tlsca.management.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/management.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls" --enrollment.profile tls --csr.hosts orderer.management.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/management.com/orderers/orderer.management.com/msp/tlscacerts/tlsca.management.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/management.com/users/Admin@management.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/management.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/management.com/users/Admin@management.com/msp/config.yaml"
}

createmanufacturer
createWasteCollectionCompany
creategovernment
createrecyclingCenter
createOrderer